-- MySQL Script generated by MySQL Workbench
-- Sun Sep 14 00:34:06 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Payments` ;

CREATE TABLE IF NOT EXISTS `Payments` (
  `idPayments` INT NOT NULL AUTO_INCREMENT,
  `BookingID` INT NOT NULL,
  `PaymentDate` DATETIME NOT NULL,
  `TotalCost` DECIMAL(10,2) NOT NULL,
  `Method` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPayments`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Booking` ;

CREATE TABLE IF NOT EXISTS `Booking` (
  `BookingID` INT NOT NULL AUTO_INCREMENT,
  `BookingDate` DATETIME NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `TotalCost` DECIMAL(10,2) NOT NULL,
  `CustomerID` INT NOT NULL,
  `TourID` INT NOT NULL,
  `Payments_idPayments` INT NOT NULL,
  PRIMARY KEY (`BookingID`),
  INDEX `fk_Booking_Payments1_idx` (`Payments_idPayments` ASC) VISIBLE,
  CONSTRAINT `fk_Booking_Payments1`
    FOREIGN KEY (`Payments_idPayments`)
    REFERENCES `Payments` (`idPayments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Customer` ;

CREATE TABLE IF NOT EXISTS `Customer` (
  `idCustomer` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `PhoneNumer` VARCHAR(45) NOT NULL,
  `Booking_BookingID` INT NOT NULL,
  PRIMARY KEY (`idCustomer`),
  INDEX `fk_Customer_Booking_idx` (`Booking_BookingID` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_Booking`
    FOREIGN KEY (`Booking_BookingID`)
    REFERENCES `Booking` (`BookingID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Guide`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Guide` ;

CREATE TABLE IF NOT EXISTS `Guide` (
  `idGuide` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGuide`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tour`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tour` ;

CREATE TABLE IF NOT EXISTS `Tour` (
  `idTour` INT NOT NULL AUTO_INCREMENT,
  `TourName` VARCHAR(45) NOT NULL,
  `Price` DECIMAL(10,2) NOT NULL,
  `Booking_BookingID` INT NOT NULL,
  `GuideID` INT NOT NULL,
  `Guide_idGuide` INT NOT NULL,
  PRIMARY KEY (`idTour`, `Booking_BookingID`, `Guide_idGuide`),
  INDEX `fk_Tour_Booking1_idx` (`Booking_BookingID` ASC) VISIBLE,
  INDEX `fk_Tour_Guide1_idx` (`Guide_idGuide` ASC) VISIBLE,
  CONSTRAINT `fk_Tour_Booking1`
    FOREIGN KEY (`Booking_BookingID`)
    REFERENCES `Booking` (`BookingID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tour_Guide1`
    FOREIGN KEY (`Guide_idGuide`)
    REFERENCES `Guide` (`idGuide`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
